# Generated by Django 4.1 on 2024-01-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
